import Head from "next/head";
import Hero from "../components/Hero";
import Feature from "../components/Feature";
import About from "../components/About";
import StartSummarize from "../components/StartSummarize";
import TeamSection from "../components/TeamSection";

export default function Home() {
  return (
    <>
      <Head>
        <title>STM</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero></Hero>
      <Feature></Feature>
      <About></About>
      <StartSummarize></StartSummarize>
      <TeamSection></TeamSection>
    </>
  );
}
